### PR TITLE
Create new installation of Windows requirements 

### PR DESCRIPTION
**Pull request by Ekultek**
* Created a build folder that will install the requirements for Windows users
* Create a `.gitignore`
* Edited the `main.py` file to see if the installations have taken place yet

Fix issue #14

### CODE REVIEW

**Comment by Ekultek** [comment]
Edited the files so that the installation will only run on Windows

**Comment by Themercee** [comment]
You main.py installation won't work, because you try to install it after the first import that actually need those dependencies. Also, I try to call you main method manually and get a shitload of error message, because Microsoft Visual C++ 9.0 is required.

**Comment by Ekultek** [comment]
The main installation runs off of standard library, and doesn't require any dependents. Visual C++ should not be required unless you're trying to run the application itself. Post the errors

**Comment by Ekultek** [comment]
Also there is no main.py in the installation package, so what are you talking about?

**Pull request closed without merging**
